# Generated by Django 5.1.1 on 2024-09-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0004_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='rows',
            name='floor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PMS.floor'),
            preserve_default=False,
        ),
    ]
