# Generated by Django 5.1.1 on 2024-09-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0005_rows_floor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rows',
            name='total_rows',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
