# Generated by Django 5.1.1 on 2024-09-27 10:24

import PMS.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0006_rows_total_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='total_columns',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(max_length=50, verbose_name=PMS.models.Rows)),
                ('column_name', models.CharField(max_length=40)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.building')),
                ('floor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.floor')),
            ],
        ),
    ]
