# Generated by Django 5.1.1 on 2024-09-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0008_building_total_floors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rows',
            name='total_rows',
        ),
    ]
