# Generated by Django 5.1.1 on 2024-09-27 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0009_remove_rows_total_rows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='row_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.rows'),
        ),
    ]
