# Generated by Django 5.1.1 on 2024-10-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0012_alter_vehical_vehical_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.building')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.column')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.floor')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.rows')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.vehical')),
            ],
        ),
    ]
